[phases.setup]
nixPkgs = ["nodejs_20", "bun", "caddy"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build:pages"]

[start]
cmd = "caddy file-server --root dist/client --listen 0.0.0.0:${PORT:-3000}"
